dist: xenial
language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- 'pypy3'
install:
- pip install --quiet --upgrade coveralls pytest
script: coverage run --source nested_diff setup.py test
sudo: false
after_success:
- coveralls
notifications:
  email: false
