language: python
python:
- '3.4'
- '3.5'
- '3.6'
- 'pypy3'
matrix:
  include:
  - python: 3.7
    dist: xenial
install:
- pip install --quiet --upgrade coveralls pytest
script: coverage run --source nested_diff setup.py test
sudo: false
after_success:
- coveralls
notifications:
  email: false
