dist: xenial
language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- 'pypy3'
matrix:
  include:
    - python: '3.8'
      script: coverage run --source nested_diff setup.py test
      after_success:
      - coveralls
install:
- pip install --quiet --upgrade coveralls pytest
script: python setup.py test
sudo: false
notifications:
  email: false
